"""add similarity fields to resolution attempts

Revision ID: 08873e2cd6d3
Revises: f3187b240bc6
Create Date: 2026-07-09 00:27:51.743243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08873e2cd6d3'
down_revision: Union[str, Sequence[str], None] = 'f3187b240bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! #

    op.add_column(
        "resolution_attempts",
        sa.Column("scene_similarity", sa.Float(), nullable=True),
    )

    op.add_column(
        "resolution_attempts",
        sa.Column("same_scene", sa.Boolean(), nullable=True),
    )

    op.add_column(
        "resolution_attempts",
        sa.Column("yolo_issue_found", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("resolution_attempts", "yolo_issue_found")
    op.drop_column("resolution_attempts", "same_scene")
    op.drop_column("resolution_attempts", "scene_similarity")

    op.drop_column("resolution_ai_results", "yolo_issue_found")
    op.drop_column("resolution_ai_results", "same_scene")
    op.drop_column("resolution_ai_results", "scene_similarity")
    op.drop_column("resolution_ai_results", "attempt_number")
    # ### end Alembic commands ###
