"""add_report_support_system

Revision ID: 29a8e5dd6b51
Revises: fa51e4681506
Create Date: 2026-07-13 01:47:54.686536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a8e5dd6b51'
down_revision: Union[str, Sequence[str], None] = 'fa51e4681506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_supports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("citizen_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["citizen_id"],
            ["users.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id",
            "citizen_id",
            name="uq_report_support",
        ),
    )
    op.create_index(op.f('ix_report_supports_id'), 'report_supports', ['id'], unique=False)
    op.add_column('reports', sa.Column('support_count', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'support_count')
    op.drop_index(op.f('ix_report_supports_id'), table_name='report_supports')
    op.drop_table('report_supports')
    # ### end Alembic commands ###
