"""add work started fields

Revision ID: 539cbea64020
Revises: 29a8e5dd6b51
Create Date: 2026-07-13 22:11:42.306746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539cbea64020'
down_revision: Union[str, Sequence[str], None] = '29a8e5dd6b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('work_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assignments', sa.Column('work_started_latitude', sa.Float(), nullable=True))
    op.add_column('assignments', sa.Column('work_started_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'work_started_longitude')
    op.drop_column('assignments', 'work_started_latitude')
    op.drop_column('assignments', 'work_started_at')
    # ### end Alembic commands ###
