"""add_department_forward_requests

Revision ID: 7f58753854ad
Revises: 9dca266dae7a
Create Date: 2026-07-16 00:59:51.839704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f58753854ad'
down_revision: Union[str, Sequence[str], None] = '9dca266dae7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_forward_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('current_department_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='forwardrequeststatus'), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['current_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_forward_requests_id'), 'department_forward_requests', ['id'], unique=False)
    op.create_index(op.f('ix_department_forward_requests_report_id'), 'department_forward_requests', ['report_id'], unique=False)
    op.create_index(op.f('ix_department_forward_requests_worker_id'), 'department_forward_requests', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_forward_requests_worker_id'), table_name='department_forward_requests')
    op.drop_index(op.f('ix_department_forward_requests_report_id'), table_name='department_forward_requests')
    op.drop_index(op.f('ix_department_forward_requests_id'), table_name='department_forward_requests')
    op.drop_table('department_forward_requests')
    # ### end Alembic commands ###
