"""add report forward history

Revision ID: 9dca266dae7a
Revises: 4b7aaa61c43d
Create Date: 2026-07-15 20:05:04.281511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dca266dae7a'
down_revision: Union[str, Sequence[str], None] = '4b7aaa61c43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_forward_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('forward_number', sa.Integer(), nullable=False),
    sa.Column('from_department_id', sa.Integer(), nullable=False),
    sa.Column('to_department_id', sa.Integer(), nullable=False),
    sa.Column('forwarded_by', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('reason_type', sa.Enum('WRONG_AI_CLASSIFICATION', 'WRONG_CITIZEN_CATEGORY', 'ADMINISTRATIVE_TRANSFER', 'DUPLICATE_DEPARTMENT', 'OTHER', name='forwardreasontype'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['forwarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_forward_history_id'), 'report_forward_history', ['id'], unique=False)
    op.add_column('reports', sa.Column('forward_count', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'forward_count')
    op.drop_index(op.f('ix_report_forward_history_id'), table_name='report_forward_history')
    op.drop_table('report_forward_history')
    # ### end Alembic commands ###
