"""Add metadata fields to report images

Revision ID: a07388429964
Revises: d49e833cb1c4
Create Date: 2026-07-04 21:43:58.814081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07388429964'
down_revision: Union[str, Sequence[str], None] = 'd49e833cb1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_images', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('report_images', sa.Column('stored_filename', sa.String(length=255), nullable=False))
    op.add_column('report_images', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('report_images', sa.Column('file_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_images', 'file_size')
    op.drop_column('report_images', 'mime_type')
    op.drop_column('report_images', 'stored_filename')
    op.drop_column('report_images', 'original_filename')
    # ### end Alembic commands ###
