"""add resolution attempts

Revision ID: f3187b240bc6
Revises: 69073d4fd979
Create Date: 2026-07-08 01:05:38.424934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3187b240bc6'
down_revision: Union[str, Sequence[str], None] = '69073d4fd979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('annotated_image_path', sa.String(), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('verification_decision', sa.String(length=30), nullable=True),
    sa.Column('ai_decision', sa.String(length=30), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('manual_review', sa.Boolean(), nullable=False, server_default=sa.text("0")),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_attempts_resolution_id'), 'resolution_attempts', ['resolution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_attempts_resolution_id'), table_name='resolution_attempts')
    op.drop_table('resolution_attempts')
    # ### end Alembic commands ###
