"""Add department_id to users

Revision ID: fa51e4681506
Revises: a6496c87c2f3
Create Date: 2026-07-10 21:02:07.875902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa51e4681506'
down_revision: Union[str, Sequence[str], None] = 'a6496c87c2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('department_id', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None,
        'users',
        type_='foreignkey',
    )
    # ### end Alembic commands ###
