"""enhance resolution verification

Revision ID: fd2eeb29324a
Revises: 7240c5d78cde
Create Date: 2026-07-06 16:50:01.385508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2eeb29324a'
down_revision: Union[str, Sequence[str], None] = '7240c5d78cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resolutions', sa.Column('verification_score', sa.Float(), nullable=True))
    op.add_column('resolutions', sa.Column('verification_decision', sa.Enum('PASS', 'REVIEW', 'REJECT', name='verificationdecision'), nullable=True))
    op.add_column('resolutions', sa.Column('manual_review', sa.Boolean(), nullable=False))
    op.add_column('resolutions', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resolutions', 'verified_at')
    op.drop_column('resolutions', 'manual_review')
    op.drop_column('resolutions', 'verification_decision')
    op.drop_column('resolutions', 'verification_score')
    # ### end Alembic commands ###
